# Uncomment the next line to define a global platform for your project
# platform :ios, '16.2'

target 'CountdownClock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountdownClock
  pod 'CropViewController'
  target 'CountdownClockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountdownClockUITests' do
    # Pods for testing
  end

end

target 'CountdownWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountdownWidgetExtension

end

target 'CountdownWidgetIntentExt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountdownWidgetIntentExt

end

target 'CountdownWidgetIntentExtUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountdownWidgetIntentExtUI

end
